### ISSUE TITLE
在helium上遇到点问题，来请教一下

### ISSUE THREAD

**Issue by purepoorx** [mybdye/Project-E#3]
helium.ComboBox 这个方法怎么用？比如现在我有一个select下拉框，如下
`<select id="country">
    <option value="us">America</option>
    <option value="cn">China</option>
    <option value="jp">Japan</option>
</select>`

请问怎么才能设置选中cn这个选项？大佬帮忙指点一下

**Comment by mybdye** [comment]
https://github.com/mherrmann/selenium-python-helium/blob/master/helium/__init__.py

查找关键字 `combobox`
